# List of Bukkit BlockFace directions check for a chest. See JavaDoc for direction names:
# http://jd.bukkit.org/rb/apidocs/org/bukkit/block/BlockFace.html
# Chests will only be used if found in these directions
# Addtionally this defines the order that chests are searched
# with the first one found being opened
check_faces: [UP, DOWN, NORTH, SOUTH, EAST, WEST]
