# List of Bukkit BlockFace directions check for a chest. See JavaDoc for direction names:
# http://jd.bukkit.org/rb/apidocs/org/bukkit/block/BlockFace.html
# Chests will only be used if found in these directions
# Addtionally this defines the order that chests are searched
# with the first one found being opened
check_faces: [UP, DOWN, NORTH, SOUTH, EAST, WEST]

# Defines which inventory holders are allowed to be linked
# with a bookshelf. Supported names are:
# BREWING_STAND, CHEST, DISPENSER, FURNACE
valid_holders: [BREWING_STAND, CHEST, DISPENSER, DROPPER, FURNACE, HOPPER, TRAPPED_CHEST, ENDER_CHEST]
