# List of Bukkit BlockFace directions check for a chest. See JavaDoc for direction names:
# http://jd.bukkit.org/rb/apidocs/org/bukkit/block/BlockFace.html
# Chests will not be used if found in these directions
check_faces: [UP, DOWN, NORTH, SOUTH, EAST, WEST]
